### ISSUE TITLE
packed_freelist

### ISSUE THREAD

**Issue by mfiano** [nlguillemot/fictional-doodle#1]
I stumbled on your blog and ended up here looking for your implementation of BitSquid's packed-array (which you call a packed_freelist in your article). Can you point me to your implementation code please? Thanks :)

**Comment by nlguillemot** [comment]
here's an implementation: https://github.com/nlguillemot/dof/blob/master/viewer/packed_freelist.h

Like the comment says in the header, it has not been tested very much, so please don't use it in production as-is.
